"""sync schema (add metrics & other drift)

Revision ID: 649a0b2194d8
Revises: 8c3a70414b9f
Create Date: 2025-08-20 23:18:27.899354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649a0b2194d8'
down_revision = '8c3a70414b9f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
