"""sync schema (add sources.handle and other drift)

Revision ID: 8c3a70414b9f
Revises: c2485870ad74
Create Date: 2025-08-20 23:09:14.182051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3a70414b9f'
down_revision = 'c2485870ad74'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('handle', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'handle')
    # ### end Alembic commands ###
