"""sync schema

Revision ID: b84b4b86b91d
Revises: 649a0b2194d8
Create Date: 2025-08-20 23:26:15.280817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84b4b86b91d'
down_revision = '649a0b2194d8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
